language: python
python:
  - "3.5"
install:
  - pip install -e .
  - python setup.py install
script: 
  - cusatexams fetch 12140821 7 November 2016 Regular
  - cusatexams batch 12140800 12140929 7 November 2016 Regular

